"""empty message

Revision ID: 3c47f26c8918
Revises: f9f2a51a5255
Create Date: 2018-03-17 15:14:38.926259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c47f26c8918'
down_revision = 'f9f2a51a5255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('confirmd', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=1) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
